# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# DEMtoSubcatchment1.py
# Created on: 2023-06-24 12:50:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")


# Local variables:
DEM_Input = "Mosaiced.img"
Filled_DEM = "C:\\Users\\M Kress\\OneDrive - csi.cuny.edu\\Documents\\ArcGIS\\Default.gdb\\Fill_img2"
Output_drop_raster = ""
Direction = "C:\\Users\\M Kress\\OneDrive - csi.cuny.edu\\Documents\\ArcGIS\\Default.gdb\\FlowDir_Fill2"
NthOutF = "NthOutF"
Accumulation = "C:\\Users\\M Kress\\OneDrive - csi.cuny.edu\\Documents\\ArcGIS\\Default.gdb\\FlowAcc_Flow2"
SnapPourPt = "C:\\Users\\M Kress\\OneDrive - csi.cuny.edu\\Documents\\ArcGIS\\Default.gdb\\SnapPou_shp8"
Subcatchment = "C:\\Users\\M Kress\\OneDrive - csi.cuny.edu\\Documents\\ArcGIS\\Default.gdb\\Watersh_Flow4"
NWtrShd2 = "C:\\Users\\M Kress\\OneDrive - csi.cuny.edu\\Documents\\ArcGIS\\Default.gdb\\NWtrShd2"
Area = NWtrShd2
Flow_Slope = "C:\\Users\\M Kress\\OneDrive - csi.cuny.edu\\Documents\\ArcGIS\\Default.gdb\\Slope_FlowDi1"
MaskedSlope = "C:\\Users\\M Kress\\OneDrive - csi.cuny.edu\\Documents\\ArcGIS\\Default.gdb\\Extract_Slop1"
MeanSlope = "18.0566748842181"

# Process: Fill
arcpy.gp.Fill_sa(DEM_Input, Filled_DEM, "")

# Process: Flow Direction
arcpy.gp.FlowDirection_sa(Filled_DEM, Direction, "NORMAL", Output_drop_raster, "D8")

# Process: Flow Accumulation
arcpy.gp.FlowAccumulation_sa(Direction, Accumulation, "", "FLOAT", "D8")

# Process: Snap Pour Point
arcpy.gp.SnapPourPoint_sa(NthOutF, Accumulation, SnapPourPt, "1", "Id")

# Process: Watershed
arcpy.gp.Watershed_sa(Direction, SnapPourPt, Subcatchment, "")

# Process: Raster to Polygon
tempEnvironment0 = arcpy.env.outputZFlag
arcpy.env.outputZFlag = "Disabled"
tempEnvironment1 = arcpy.env.outputMFlag
arcpy.env.outputMFlag = "Disabled"
arcpy.RasterToPolygon_conversion(Subcatchment, NWtrShd2, "SIMPLIFY", "Value", "SINGLE_OUTER_PART", "")
arcpy.env.outputZFlag = tempEnvironment0
arcpy.env.outputMFlag = tempEnvironment1

# Process: Get Field Value
arcpy.GetFieldValue_mb(NWtrShd2, "Shape_Area", "String", "0")

# Process: Slope
arcpy.gp.Slope_sa(Direction, Flow_Slope, "DEGREE", "1", "PLANAR", "METER")

# Process: Extract by Mask
arcpy.gp.ExtractByMask_sa(Flow_Slope, NWtrShd2, MaskedSlope)

# Process: Get Raster Properties
arcpy.GetRasterProperties_management(MaskedSlope, "MEAN", "")

