%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Zhanyang\SensorData\CompoundFlooding\CompoundFloodModel\MesoNetSensorComparison\JanFeb2023App\PlotInFeet\dfData.csv
%
% Auto-generated by MATLAB on 2023/09/23 12:46:37.09

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["time", "depth"];
opts.VariableTypes = ["datetime", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "time", "InputFormat", "yyyy-MM-dd HH:mm:ss");

% Import the data
dfData = readtable("C:\Zhanyang\SensorData\CompoundFlooding\CompoundFloodModel\MesoNetSensorComparison\JanFeb2023App\PlotInFeet\dfData.csv", opts);

%
%   Set the time zone for the time data.
%
dfData.time.TimeZone='America/New_York';
%% Clear temporary variables
clear opts